import {
  Links,
  LiveReload,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
  useLoaderData,
  useRouteError,
} from "@remix-run/react"
import { Analytics } from "@vercel/analytics/react"
import { json } from "@vercel/remix"
import type { HeadersFunction, LinksFunction } from "@vercel/remix"
import { SpeedInsights } from "@vercel/speed-insights/remix"
import type { PropsWithChildren } from "react"

import type { Env } from "~/browser-globals"
import { AppError } from "~/components/AppError"
import { Layout } from "~/components/Layout"
import { TURNSTILE_SITE_KEY } from "~/services/captcha.server"

import styles from "./tailwind.css"

export const links: LinksFunction = () => [
  { rel: "stylesheet", href: styles },
  { rel: "preconnect", href: "https://rsms.me/" },
  { rel: "stylesheet", href: "https://rsms.me/inter/inter.css" },
]

export const headers: HeadersFunction = () => {
  // Default set of headers used for data requests.
  const clientMaxAge = 60 * 30 // 30 minutes
  const cdnMaxAge = 60 * 60 // 1 hour
  const revalidationPeriod = 60 * 5 // 5 minutes
  return {
    "Cache-Control": `max-age=${clientMaxAge}, s-maxage=${cdnMaxAge}, stale-while-revalidate=${revalidationPeriod}`,
  }
}

export async function loader() {
  return json({
    ENV: {
      TURNSTILE_SITE_KEY,
    } as Env,
  })
}

function App({ title, children }: PropsWithChildren<{ title?: string }>) {
  // Title is generated by Remix in each route, so ignore it here
  // unless explicitly provided.
  // noinspection HtmlRequiredTitleElement
  return (
    // Always start with the "dark" class, so we don't flash-bang our dark mode users while the JS loads.
    <html lang="en" className="dark h-full antialiased">
      <head>
        {title && <title>{title}</title>}
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Meta />
        <Links />
      </head>
      <body className="h-full w-full bg-zinc-50 text-zinc-600 dark:bg-black dark:text-zinc-400">
        <Layout>{children}</Layout>
        <ScrollRestoration />
        <Scripts />
        <SpeedInsights />
        <Analytics />
        <LiveReload />
      </body>
    </html>
  )
}

export default function Root() {
  const { ENV } = useLoaderData<typeof loader>()

  return (
    <App>
      <Outlet context={ENV} />
    </App>
  )
}

export function ErrorBoundary() {
  const error = useRouteError()
  console.error(error)

  return (
    <App title="Whoops :/">
      <AppError
        code={500}
        title="Server error"
        description="We ran into a problem while trying to fulfill your request. Please try again later."
      />
    </App>
  )
}
